# generic settings
vagrant_box: debian/contrib-jessie64
vagrant_disksize: 20GB
# box specific settings
## base box setings
vagrant_box_base: ubuntu/focal64
## Application Server settings
vagrant_ip_server: 192.168.50.10
vagrant_memory_server: 4096
vagrant_cpu_server: 4
vagrant_hostname_server: app-server
vagrant_vmname_server: app-server
## Modernaize settings
vagrant_ip_modernaize: 192.168.50.11
vagrant_memory_modernaize: 8192
vagrant_cpu_modernaize: 4
vagrant_hostname_modernaize: modernaize-server
vagrant_vmname_modernaize: modernaize
vagrant_base_box_modernaize: base-server-ubuntu-2004
vagrant_vm_name_modernaize: modernaize
