version: '2.1'
services:
  license:
    image: liveobjects/license-service:${LIC_VERSION}
    container_name: license-service
    ports:
      - "3001:3001"
      - "9992:9991"
    env_file:
      - ./.env
    restart: always
    volumes:
      - ${LICENSE_DIR}/license:/home/node/app/license/lo
    depends_on:
      db:
        condition: service_healthy

  db:
    image: liveobjects/postgres:${POSTGRES_VERSION}
    container_name: postgre
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liveobjects"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${PGDATA_DIR}/pgdata:/var/lib/postgresql/data
    restart: always

  ui:
    image: liveobjects/ui:${UI_VERSION}
    container_name: ui
    ports:
      - "443:3000"
      - "9991:9991"
    env_file:
      - ./.env
    volumes:
      - ${TLSKEYS_DIR}/keys/tls:/home/node/app/keys/tls
      - ${LOGS_DIR}/logs/ui:/home/node/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:3000/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  servicebackend:
    image: liveobjects/service:${SERVICE_VERSION}
    container_name: service
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ${TLSKEYS_DIR}/keys/tls:/mnt/keys
      - ${LOGS_DIR}/logs:/mnt/logs      
      - ${LODATA_DIR}/data/uploads:/mnt/uploads
      - ${LODATA_DIR}/data/data:/mnt/data
    restart: always

  servicelearn:
    image: liveobjects/learn:${ML_VERSION}
    container_name: learn
    command: gunicorn --workers=2  --worker-tmp-dir /dev/shm -c gunicorn_config.py --bind 0.0.0.0:5000 wsgi:APP
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - 
    volumes:
      - ${LODATA_DIR}/data/uns_model:/tmp
      - ${LODATA_DIR}/data/uns_model/uploads:/tmp/uploads
      - ${LODATA_DIR}/data/procmine:/mnt/procmine
      - ${LOGS_DIR}/logs:/mnt/logs
    restart: always

  scenario:
    image: liveobjects/lo-ui-scenario:${UI_SCENARIO_VERSION}
    container_name: scenario
    ports:
      - "3002:3002"
    env_file:
      - ./.env
    volumes:
      - ${LOGS_DIR}/logs/scenario:/home/node/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:3002/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  uidashboards:
    image: liveobjects/lo-ui-dashboards:${UI_DASHBOARDS_VERSION}
    container_name: uidashboards
    depends_on:
      - servicebackend
    ports:
      - "3005:3005"
    env_file:
      - ./.env
    volumes:
      - ${LOGS_DIR}/logs/uidashboards:/home/node/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:3005/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  wdc:
    image: liveobjects/lo-tableau-wdc:${UI_WDC_VERSION}
    container_name: wdc
    env_file:
      - ./.env
    ports:
      - "5001:5001"
    restart: always

  dyk:
    image: liveobjects/lo-ui-dyk:${UI_DYK}
    container_name: dyk
    env_file:
      - ./.env
    ports:
      - "3003:3003"
    volumes:
      - ${LOGS_DIR}/logs/dyk:/home/node/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:3003/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  businessgrammar:
    image: liveobjects/lo-ui-business-grammar:${UI_BUSINESS_GRAMMAR}
    container_name: businessgrammar
    env_file:
      - ./.env
    ports:
      - "3007:3007"
    volumes:
      - ${LOGS_DIR}/logs/businessgrammar:/home/node/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:3007/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  extension:
    image: liveobjects/lo-ui-extensions:${UI_EXTENSION}
    container_name: extension
    env_file:
      - ./.env
    ports:
      - "3008:3008"
    volumes:
      - ${LOGS_DIR}/logs/extension:/home/node/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:3008/live"]
      interval: 10s
      timeout: 5s
      retries: 3

