version: "3"
services:
  db:
    image: liveobjects/install-postgres:${POSTGRES_VERSION}
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ${DATA}/postgresql/data:/var/lib/postgresql/data
    restart: always
  ui:
    image: liveobjects/ui:${UI_VERSION}
    ports:
      - "443:3000"
    environment:
      - SERVICE_HOST=servicebackend
      - SERVICE_PORT=8000
      - LEARN_HOST=servicelearn
      - LEARN_PORT=5000
      - NODE_ENV=production
      - TLS_CERT_PROVIDED=true
    volumes:
      - ./license:/opt/node/license/lo
      - ./keys/tls:/opt/node/keys/tls
    restart: always
  servicebackend:
    image: liveobjects/service:${SERVICE_VERSION}
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - LEARN_HOST=servicelearn
      - LEARN_PORT=5000
    volumes:
      - ./logs:/mnt/logs
      - ./keys:/mnt/keys
      - ./data/uploads:/mnt/uploads
      - ./data/data:/mnt/data
    restart: always
  servicelearn:
    image: liveobjects/learn:${ML_VERSION}
    command: gunicorn --workers=2  --worker-tmp-dir /dev/shm  --bind 0.0.0.0:5000 wsgi:APP
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    environment:
      - FLASK_APP=server.py
      - DB_HOST=db
      - DB_PORT=5432
      - FLASK_ENV=production
    volumes:
      - ./data/uns_model:/tmp
      - ./data/uns_model/uploads:/tmp/uploads
      - ./data/procmine:/mnt/procmine
      - ./logs:/mnt/logs
    restart: always
