version: '2.1'
services:
  license:
    image: liveobjects/license-service:${LIC_VERSION}
    container_name: license-service
    ports:
      - "3001:3001"
      - "9992:9991"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./license:/home/node/app/license/lo

    depends_on:
      db:
        condition: service_healthy
  db:
    image: liveobjects/postgres:${POSTGRES_VERSION}
    container_name: postgre
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liveobjects"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env
    volumes:
      - ${DATA}/postgresql/data:/var/lib/postgresql/data
    restart: always

  ui:
    image: liveobjects/ui:${UI_VERSION}
    ports:
      - "443:3000"
      - "9991:9991"
    env_file:
      - ./.env
    volumes:
      - ./keys/tls:/home/node/app/keys/tls
      - ./logs:/home/node/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost:3000/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  servicebackend:
    image: liveobjects/service:${SERVICE_VERSION}
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./logs:/mnt/logs
      - ./keys:/mnt/keys
      - ./data/uploads:/mnt/uploads
      - ./data/data:/mnt/data
    restart: always

  servicelearn:
    image: liveobjects/learn:${ML_VERSION}
    container_name: learn
    command: gunicorn --workers=2  --worker-tmp-dir /dev/shm -c gunicorn_config.py --bind 0.0.0.0:5000 wsgi:APP
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./data/uns_model:/tmp
      - ./data/uns_model/uploads:/tmp/uploads
      - ./data/procmine:/mnt/procmine
      - ./logs:/mnt/logs
    restart: always

  scenario:
    image: liveobjects/lo-ui-scenario:${UI_SCENARIO_VERSION}
    container_name: scenario
    ports:
      - "3002:3002"
    volumes:
      - ./logs:/home/node/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:3002/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - db
    env_file:
      - ./.env


  uidashboards:
    image: liveobjects/lo-ui-dashboards:${DASHBOARD_VERSION}
    container_name: uidashboards
    ports:
      - "3005:3005"
    volumes:
      - ./logs:/home/node/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:3005/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - servicebackend
    env_file:
      - ./.env
  wdc:
    image: liveobjects/lo-tableau-wdc:${WDC_VERSION}
    container_name: wdc
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - servicebackend
    env_file:
      - ./.env

  dyk:
    image: liveobjects/lo-ui-dyk:${UI_DYK}
    container_name: dyk
    ports:
      - "3003:3003"
    volumes:
      - ./logs:/home/node/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost:3003/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - servicebackend
    env_file:
      - ./.env

  businessgrammar:
    image: liveobjects/lo-ui-business-grammar:${UI_BUSINESS_GRAMMAR}
    container_name: businessgrammar
    ports:
      - "3007:3007"
    volumes:
      - ./logs:/home/node/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:3007/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - servicebackend
    env_file:
      - ./.env

  extension:
    image: liveobjects/lo-ui-extensions:${UI_EXTENSION}
    container_name: extension
    ports:
      - "3008:3008"
    volumes:
      - ./logs:/home/node/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost:3008/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - servicebackend
    env_file:
      - ./.env



