---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ template "loServer.secretName" . }}
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/appVersion: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: secret
    app.kubernetes.io/helm-application: {{ .Release.Name }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    track: "stable"
type: OPague
# $ echo FOO | base64
# Rk9PCg==
# $ echo Rk9PCg== | base64 -d
# FOO
data:
  adminPassword: {{ include "loServer.adminPassword" . | b64enc | quote }}
  license_adminPassword: {{ include "loServer.license_adminPassword" . | b64enc | quote }}
  rootPassword: {{ include "loServer.rootPassword" . | b64enc | quote }}
  system_adminPassword: {{ include "loServer.system_adminPassword" . | b64enc | quote }}
---
{{- if eq (lower .Values.lo.sslConfiguration) "self-signed" }}
{{- if .Values.tls.base64EncodedPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lo-custom-tls
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/appVersion: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: secret
    app.kubernetes.io/helm-application: {{ .Release.Name }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    track: "stable"
data:
  key.pem: |
    {{- .Values.tls.base64EncodedPrivateKey | nindent 4 }}
  cert.pem: |
    {{- .Values.tls.base64EncodedCertificate | nindent 4 }}
{{- end }}
{{- end }}