apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.secretName" . }}
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/appVersion: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: secret
    app.kubernetes.io/helm-application: {{ .Release.Name }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    track: "stable"
type: OPague
# $ echo FOO | base64
# Rk9PCg==
# $ echo Rk9PCg== | base64 -d
# FOO
data:
  username: bGl2ZW9iamVjdHM=
  password: {{ include "postgresql.password" . | b64enc | quote }}
