# Source: postgresql/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.postgres.metadata.name }}
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/appVersion: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: secret
    app.kubernetes.io/helm-application: {{ .Release.Name }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    track: "stable"
spec:
  type: {{ .Values.services.postgres.spec.type }}
  ports:
    - name: tcp-postgresql
      port: {{ .Values.deployment.postgres.container.ports.containerPort }}
      targetPort: tcp-postgresql
  selector:
    app: postgresql
    release: "pg"
