{{- if .Values.global.dockerSecret }}
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJsaXZlb2JqZWN0cyIsInBhc3N3b3JkIjoiYjc2YjM1Ny1jYjYwLTRkYWUtOGQ0Zi1iZThmMTRhN2I1YWMiLCJhdXRoIjoiYkdsMlpXOWlhbVZqZEhNNllqYzJZak0xTnkxallqWXdMVFJrWVdVdE9HUTBaaTFpWlRobU1UUmhOMkkxWVdNPSJ9fX0=
kind: Secret
metadata:
  name: {{ .Release.Name }}-regcred
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/appVersion: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: secret
    app.kubernetes.io/helm-application: {{ .Release.Name }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    track: "stable"
type: kubernetes.io/dockerconfigjson
{{- end }}