{{- if .Values.ingress.tls.host }}
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ui-extensions-ingress
  annotations:
  {{- if eq (lower .Values.lo.sslConfiguration) "lets-encrypt" }}
    cert-manager.io/cluster-issuer: {{ .Release.Namespace }}-{{ .Values.certManager.ca.name }}-{{ .Values.certManager.letsencrypt.env }}
  {{- end }}
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/appVersion: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: secret
    app.kubernetes.io/helm-application: {{ .Release.Name }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/track: {{ .Values.global.labels.track | quote }}
spec:
  {{- if eq (lower .Values.lo.sslConfiguration) "lets-encrypt" }}
  tls:
    - hosts:
      - {{ .Values.ingress.tls.host }}
      secretName: {{ .Release.Namespace }}-{{ .Values.certManager.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.tls.host }}
      http:
        paths: 
          - path: /rp-scenario
            backend:
              serviceName: {{ .Release.Name }}-{{ .Values.services.scenario.metadata.name }}
              {{- if or (eq (lower .Values.lo.sslConfiguration ) "none") (eq (lower .Values.lo.sslConfiguration ) "lets-encrypt")  }}
              servicePort: {{ .Values.services.scenario.spec.ports.port }}
              {{- else }}
              servicePort: {{ .Values.services.scenario.spec.ports.tlsport }}
              {{- end }}
          - path: /rp-businessgrammar
            backend:
              serviceName: {{ .Release.Name }}-{{ .Values.services.businessgrammar.metadata.name }}
              {{- if or (eq (lower .Values.lo.sslConfiguration ) "none") (eq (lower .Values.lo.sslConfiguration ) "lets-encrypt")  }}
              servicePort: {{ .Values.services.businessgrammar.spec.ports.port }}
              {{- else }}
              servicePort: {{ .Values.services.businessgrammar.spec.ports.tlsport }}
              {{- end }}
          - path: /rp-dyk
            backend:
              serviceName: {{ .Release.Name }}-{{ .Values.services.dyk.metadata.name }}
              {{- if or (eq (lower .Values.lo.sslConfiguration ) "none") (eq (lower .Values.lo.sslConfiguration ) "lets-encrypt")  }}
              servicePort: {{ .Values.services.dyk.spec.ports.port }}
              {{- else }}
              servicePort: {{ .Values.services.dyk.spec.ports.tlsport }}
              {{- end }}
          - path: /rp-dashboards
            backend:
              serviceName: {{ .Release.Name }}-{{ .Values.services.dashboards.metadata.name }}
              {{- if or (eq (lower .Values.lo.sslConfiguration ) "none") (eq (lower .Values.lo.sslConfiguration ) "lets-encrypt")  }}
              servicePort: {{ .Values.services.dashboards.spec.ports.port }}
              {{- else }}
              servicePort: {{ .Values.services.dashboards.spec.ports.tlsport }}
              {{- end }}
          - path: /rp-extensions
            backend:
              serviceName: {{ .Release.Name }}-{{ .Values.services.extensions.metadata.name }}
              {{- if or (eq (lower .Values.lo.sslConfiguration ) "none") (eq (lower .Values.lo.sslConfiguration ) "lets-encrypt")  }}
              servicePort: {{ .Values.services.extensions.spec.ports.port }}
              {{- else }}
              servicePort: {{ .Values.services.extensions.spec.ports.tlsport }}
              {{- end }}
          - path: /rp-autojoin
            backend:
              serviceName: {{ .Release.Name }}-{{ .Values.services.discoveryautojoin.metadata.name }}
              {{- if or (eq (lower .Values.lo.sslConfiguration ) "none") (eq (lower .Values.lo.sslConfiguration ) "lets-encrypt")  }}
              servicePort: {{ .Values.services.discoveryautojoin.spec.ports.port }}
              {{- else }}
              servicePort: {{ .Values.services.discoveryautojoin.spec.ports.tlsport }}
              {{- end }}
          - path: /rp-documentation
            backend:
              serviceName: {{ .Release.Name }}-{{ .Values.services.documentation.metadata.name }}
              {{- if or (eq (lower .Values.lo.sslConfiguration ) "none") (eq (lower .Values.lo.sslConfiguration ) "lets-encrypt")  }}
              servicePort: {{ .Values.services.documentation.spec.ports.port }}
              {{- else }}
              servicePort: {{ .Values.services.documentation.spec.ports.tlsport }}
              {{- end }}
          - path: /wdc
            backend:
              serviceName: {{ .Release.Name }}-{{ .Values.services.wdc.metadata.name }}
              {{- if or (eq (lower .Values.lo.sslConfiguration ) "none") (eq (lower .Values.lo.sslConfiguration ) "lets-encrypt")  }}
              servicePort: {{ .Values.services.wdc.spec.ports.port }}
              {{- else }}
              servicePort: {{ .Values.services.wdc.spec.ports.tlsport }}
              {{- end }}

{{- end }}
